### ISSUE TITLE
Prototype Issue Ranking Page

### ISSUE THREAD

**Issue by m-d-s** [psu-capstone/churchill#41]
Develop a demo issue ranking page that will allow users to input values between [-2,2]. Each inputed value will be correlated to a string value that represents a given value, objective, or policy.

**Comment by rebpdx** [comment]
@ScienceRobot and @m-d-s After much reading on the internet about the woes of using JQuery with Angular I found out that AngularUI has done the work to incorporate the sortable already so I'll be looking into integrating that instead this afternoon. https://github.com/angular-ui/ui-sortable

**Comment by m-d-s** [comment]
Sounds good dude. I think Ryan was planning on introducing that library so
feel free to utilize it and push it up
