### ISSUE TITLE
Dynamically supply row titles to stacked bar chart

### ISSUE THREAD

**Issue by m-d-s** [psu-capstone/churchill#54]
Right now, the rows in the stacked bar chart are titled "Question 1, Question 2, ..." We need to allow those titles to be supplied so that they will reflect what they represent. Please ask if you need clarification on this issue.

**Comment by m-d-s** [comment]
I figured I would assign you since you said you were working on it

**Comment by rebpdx** [comment]
Have an object dynamically pulled in mapping ids to titles, called headerData. Need to ensure data ordering when binding to the C3 chart.

**Comment by rebpdx** [comment]
Titles are showing up, added new issue regarding title text overlapping in c3 chart.
