### ISSUE TITLE
extend submit button on rankings to span the width of the tabset

### ISSUE THREAD

**Issue by m-d-s** [psu-capstone/churchill#99]
maybe play around with the styling a little as well

**Comment by m-d-s** [comment]
I saw you pushed a branch up for this, were you trying to get that merged in? If so, you generally need to open a pull request so that I know you are done working on the branch. If not, feel free to keep working on it

**Comment by lafertej** [comment]
I was going to do one or two more things since the changes I made were
pretty small. Or should I try to merge with each thing/more often?

**Comment by m-d-s** [comment]
Pushing your changes up regularly is usually a good idea, you would only try to merge via a pull request when you believe your issue is complete.

**Comment by lafertej** [comment]
That's what I mean, are you wanting me to pull request between issues even
though they're so small?
